# Welcome to Jekyll!


title                    : "ARCTL.ONLINE"
title_separator          : "-"
subtitle                 : "АРК: Транспортная логистика Online"
name                     : &name "АРК: Транспортная логистика Online"
logo                     : "assets/images/LogoARCрастр.jpg" # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
email:
description              : "Специализированная информационная система комплексного управления транспортно-логистическими операциями."
minimal_mistakes_skin    : default
search                   : true

# Build settings
markdown                 : kramdown
remote_theme             : mmistakes/minimal-mistakes
# Outputting
permalink                : /:categories/:title/
paginate                 : 5 # amount of posts to show
paginate_path            : /page:num/
timezone                 : # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  links:
    - label: "Возможности"
      icon: "fas fa-book"
      url: "https://arctl.github.io/www/opportunities/"
    - label: "Преимущества"
      icon: "fas fa-check"
      url: "https://arctl.github.io/www/advantages/"
    - label: "Кто наши клиенты"
      icon: "fa fa-user-circle"
      url: "https://arctl.github.io/www/clients/"
    - label: "Запрос на подключение"
      icon: "fas fa-edit"
      url: "https://arctl.github.io/www/order/"

footer:
  links:
    - label: "telegram"
      icon: "fab fa-telegram"
      url: "https://t.me/arctl"
    - label: "Документация"
      icon: "fa fa-question-circle"
      url: "https://arctl.github.io/docs/"
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /about/
tag_archive:
  type: liquid
  path: /tags/
